
server:
  port: 8013
#  ssl:
#    key-store: keystore.p12
#    key-store-password: 123456
#    key-password: 123456
#    trust-store: d:\tomcat.keystor
#    trust-store-password: 123456
#    protocol: TLS
  undertow:
    accesslog:
      enabled: true
      dir: ./log
    io-threads: 4
    worker-threads: 32
    buffer-size: 1024
    max-http-post-size: 0
  http2:
    enabled: false

spring:
  profiles:
    active: dev
  dataSource:
    url: jdbc:mariadb://127.0.0.1:3306/test
    username: root
    password: wang
    driver-class-name: org.mariadb.jdbc.Driver
    connection-test-query: SELECT 1 FROM DUAL
    connection-timeout: 30000
    maximum-pool-size: 20
    max-lifetime: 1800000
    minimum-idle: 5

quartz:
  cronExpression: 0 * * * * ?

